vim.opt.statusline = ""
    .. "%#PmenuSel#"
    .. "%#LineNr#"
    .. "%f"
    .. "%m"
    .. "%="
    .. "%#CursorColumn#"
    .. " %y"
    .. " %{&fileencoding?&fileencoding:&encoding} "
    .. "[%{&fileformat}] "
    .. "%3p%% "
    .. "%04l/%04L:%03c/%03{strwidth(getline('.'))}"
